name: Release QBlazorAnalyzers

on:
  release:
    types:
      - published

defaults:
  run:
    working-directory: src/QBlazorAnalyzers
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Get Version
      id: version
      uses: battila7/get-version-action@v2.2.1
    - name: Pack
      run: dotnet pack -c Release -o ./artifacts --no-restore --include-source -p:PackageVersion=${{ steps.version.outputs.version-without-v }}
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./**/artifacts/*.nupkg
        file_glob: true
        tag: ${{ github.ref }}
        overwrite: true
    - name: Publish Nuget to NuGet.org registry
      run: dotnet nuget push ./**/artifacts/*.nupkg -k ${NUGET_APIKEY} -s https://api.nuget.org/v3/index.json -n true
      env:
        NUGET_APIKEY: ${{ secrets.NUGET_APIKEY }}
        
